export const GET_TASK_QUESTIONS = 'GET_TASK_QUESTIONS';
export const GET_TASK_QUESTIONS_PENDING = 'GET_TASK_QUESTIONS_PENDING';

export const CREATE_QUESTION = 'CREATE_TASK_QUESTION';
export const CREATE_QUESTION_PENDING = 'CREATE_TASK_QUESTION_PENDING';

export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const UPDATE_QUESTION_PENDING = 'UPDATE_QUESTION_PENDING';

export const CREATE_ANSWER = 'CREATE_QUESTION_ANSWER';
export const CREATE_ANSWER_PENDING = 'CREATE_QUESTION_ANSWER_PENDING';

export const UPDATE_ANSWER = 'UPDATE_ANSWER';
export const UPDATE_ANSWER_PENDING = 'UPDATE_ANSWER_PENDING';

export const GET_QUESTIONS_ERROR = 'GET_QUESTIONS_ERROR';