export const GET_TASK = 'GET_TASK';
export const GET_TASK_PENDING = 'GET_TASK_PENDING';

export const GET_TASK_ALL = 'GET_TASK_ALL';
export const GET_TASK_ALL_PENDING = 'GET_TASK_ALL_PENDING';

export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_PENDING = 'CREATE_TASK_PENDING';

export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_PENDING = 'DELETE_TASK_PENDING';

export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_PENDING = 'UPDATE_TASK_PENDING';

export const TASK_API_ERROR = 'TASK_API_ERROR';
